CREATE TABLE IF NOT EXISTS ADDRESS (
	ADDR_ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  STREET VARCHAR(200) NOT NULL,
	CITY VARCHAR(100) NOT NULL,
	STATE_CODE CHAR(2) NOT NULL,
	ZIPCODE CHAR(5) NOT NULL
);

CREATE TABLE IF NOT EXISTS USERS (
	USER_ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  USERNAME VARCHAR(50) NOT NULL UNIQUE,
  PASS_WORD VARCHAR(200) NOT NULL,
  EMAIL VARCHAR(100) NOT NULL,
  PHONE_NUMBER VARCHAR(20) NOT NULL,
  GENDER CHAR(1) NOT NULL,
  USER_DESC NVARCHAR(1000),
  PICTURE_URL NVARCHAR(1000),
  BIRTH_DATE DATE NOT NULL,
  DISPLAY_NAME VARCHAR(200) NOT NULL,
	CHECK (GENDER IN ('M' , 'F', 'X', '?'))
);


CREATE TABLE IF NOT EXISTS RENTER (
	USER_ID INT UNSIGNED PRIMARY KEY,
	FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
	ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS RENTER_SETTINGS (
  USER_ID INT UNSIGNED PRIMARY KEY,
  DISTANCE_MAX INT NOT NULL,
  GENDER_PREFERRED CHAR(1) NOT NULL,
  CHECK (GENDER_PREFERRED IN ('M' , 'F', 'X', '?')),
  FOREIGN KEY (USER_ID) 
  REFERENCES USERS (USER_ID)
  ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE IF NOT EXISTS RENTER_PREFERENCES (
  PREFERENCE_ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  PREFERENCE_NAME VARCHAR(100) NOT NULL
);


CREATE TABLE IF NOT EXISTS HAS_PREFERENCE (
  USER_ID INT UNSIGNED,
  PREFERENCE_ID INT UNSIGNED,
  CONSTRAINT PK_PREFERENCE PRIMARY KEY (USER_ID, PREFERENCE_ID),
  FOREIGN KEY (USER_ID) 
  REFERENCES USERS (USER_ID)
  ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (PREFERENCE_ID) 
  REFERENCES RENTER_PREFERENCES (PREFERENCE_ID)
);

CREATE TABLE IF NOT EXISTS LANDLORD (
	USER_ID INT UNSIGNED PRIMARY KEY,
	FOREIGN KEY (USER_ID) 
  REFERENCES USERS(USER_ID)
  ON DELETE CASCADE ON UPDATE CASCADE
);


CREATE TABLE IF NOT EXISTS MESSAGE (
	MSG_ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
	SENDER_ID INT UNSIGNED NOT NULL,
	RECIPIENT_ID INT UNSIGNED NOT NULL,
	TIME_STAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	MESSAGE_TEXTS VARCHAR(1000) CHARACTER SET utf8mb4 NOT NULL,
	IS_READ BOOL NOT NULL DEFAULT 0,
	FOREIGN KEY (SENDER_ID) 
  REFERENCES USERS(USER_ID)
  ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (RECIPIENT_ID) 
  REFERENCES USERS(USER_ID)
  ON DELETE CASCADE ON UPDATE CASCADE
);
    

CREATE TABLE IF NOT EXISTS NOTIFICATION (
  NOTIFICATION_ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT ,
  TIME_STAMP TIMESTAMP NOT NULL,
  IS_READ BOOL NOT NULL DEFAULT 0,
  NOTIFICATION_TEXT NVARCHAR(1000) NOT NULL
);

CREATE TABLE IF NOT EXISTS NOTIFIES (
	NOTIFICATION_ID INT UNSIGNED, 
  USER_ID INT UNSIGNED,
  CONSTRAINT PK_NOTIFIES PRIMARY KEY (NOTIFICATION_ID, USER_ID),
  FOREIGN KEY (NOTIFICATION_ID) 
  REFERENCES NOTIFICATION (NOTIFICATION_ID),
  FOREIGN KEY (USER_ID) 
  REFERENCES USERS (USER_ID)
);
    
    
CREATE TABLE IF NOT EXISTS PROPERTY (
	PROPERTY_ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  RENT_COST INT UNSIGNED NOT NULL,
  PROPERTY_RATING FLOAT(2, 1),
  LANDLORD_ID INT UNSIGNED,
  SQFT INT UNSIGNED,
  BATHROOMS FLOAT(2, 1) UNSIGNED,
  BEDROOMS FLOAT(2, 1) UNSIGNED,
  CAN_RENT BOOL NOT NULL,
  UNIT_LABEL VARCHAR(50),
  ADDR_ID INT UNSIGNED NOT NULL,
  FOREIGN KEY (LANDLORD_ID) 
  REFERENCES LANDLORD (USER_ID),
	FOREIGN KEY (ADDR_ID) 
		REFERENCES ADDRESS (ADDR_ID),
    CHECK (PROPERTY_RATING >= 0.0 AND PROPERTY_RATING <= 5.0)
);

CREATE TABLE IF NOT EXISTS REVIEW (
  USER_ID INT UNSIGNED,
  PROPERTY_ID INT UNSIGNED,
  COMMENTS VARCHAR(1000),
  STARS FLOAT(2, 1) UNSIGNED NOT NULL,
  CHECK (STARS BETWEEN 1 AND 5), 
  CONSTRAINT PK_REVIEW PRIMARY KEY (USER_ID, PROPERTY_ID),
  FOREIGN KEY (USER_ID)
  REFERENCES USERS (USER_ID),
  FOREIGN KEY (PROPERTY_ID)
  REFERENCES PROPERTY (PROPERTY_ID)
);

CREATE TABLE IF NOT EXISTS INTERUSER (
  RENTER_ID INT UNSIGNED,
  CONNECTION_ID INT UNSIGNED,
  SWIPED BOOL NOT NULL,
  BLOCKED BOOL NOT NULL DEFAULT 0,
  CONSTRAINT PK_INTERUSER PRIMARY KEY (RENTER_ID, CONNECTION_ID),
  FOREIGN KEY (RENTER_ID)
  REFERENCES RENTER (USER_ID)
  ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (CONNECTION_ID)
  REFERENCES RENTER (USER_ID)
  ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS SESSIONS (
  TOKEN VARCHAR(128) PRIMARY KEY,
  USER_ID INT UNSIGNED NOT NULL,
  CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  EXPIRES_AT DATETIME NOT NULL,
  FOREIGN KEY (USER_ID)
  REFERENCES USERS (USER_ID)
);