CREATE DATABASE IF NOT EXISTS MAINEPAD
  DEFAULT CHARACTER SET utf8mb4
  DEFAULT COLLATE utf8mb4_0900_ai_ci;

USE MAINEPAD;
SET profiling = 1;
SET GLOBAL sql_mode = CONCAT(@@sql_mode, ',ONLY_FULL_GROUP_BY');