DELIMITER $$

CREATE PROCEDURE ADD_PROPERTY (
    IN P_STREET VARCHAR(200),
    IN P_CITY VARCHAR(100),
    IN P_STATE_CODE CHAR(2),
    IN P_ZIP CHAR(5),
    IN P_UNIT_LABEL VARCHAR(50),
    IN P_RENT_COST INT,
    IN P_SQFT INT UNSIGNED,
    IN P_BEDROOMS FLOAT(2,1),
    IN P_BATHROOMS FLOAT(2,1),
    IN P_CAN_RENT TINYINT(1)
)
BEGIN
    DECLARE V_ADDR_ID BIGINT;
    DECLARE P_PROPERTY_ID INT;

    -- Check if the address exists
    SELECT ADDR_ID INTO V_ADDR_ID
    FROM ADDRESS
    WHERE STREET = P_STREET
      AND CITY = P_CITY
      AND STATE_CODE = P_STATE_CODE
      AND ZIPCODE = P_ZIP
    LIMIT 1;

    -- If not, insert a new address
    IF V_ADDR_ID IS NULL THEN
        INSERT INTO ADDRESS (STREET, CITY, STATE_CODE, ZIPCODE)
        VALUES (P_STREET, P_CITY, P_STATE_CODE, P_ZIP);
        SET V_ADDR_ID = LAST_INSERT_ID();
    END IF;

    -- Insert property
    INSERT INTO PROPERTY (
        UNIT_LABEL, RENT_COST, PROPERTY_RATING, LANDLORD_ID, 
        SQFT, BATHROOMS, BEDROOMS, CAN_RENT, ADDR_ID
    ) VALUES (
        P_UNIT_LABEL, P_RENT_COST, NULL, NULL,
        P_SQFT, P_BATHROOMS, P_BEDROOMS, P_CAN_RENT, V_ADDR_ID
    );

    SET P_PROPERTY_ID = LAST_INSERT_ID();
END$$

DELIMITER ;
