-- TITLE: INSERT_USER
-- AUTHOR: Ashley Pike
-- A simple stored procedure for inserting given values into a new user instance

DELIMITER $$

CREATE PROCEDURE INSERT_USER (
    -- Variables to be included
    IN p_USERNAME VARCHAR(50),
   	IN p_PASS_WORD VARCHAR(50),
	IN p_EMAIL VARCHAR(100),
    IN p_PHONE_NUMBER VARCHAR(20),
    IN p_GENDER CHAR(1),
    IN p_BIRTH_DATE DATE,
    IN p_DISPLAY_NAME VARCHAR(200),
    IN p_USER_TYPE VARCHAR(10)
)
BEGIN
    DECLARE p_USER_ID INT;

    -- Inserting values
    INSERT INTO USERS (USERNAME, PASS_WORD, EMAIL, PHONE_NUMBER, GENDER, BIRTH_DATE, DISPLAY_NAME)
    VALUES (p_USERNAME, p_PASS_WORD, p_EMAIL, p_PHONE_NUMBER, p_GENDER, p_BIRTH_DATE, p_DISPLAY_NAME);

    SET p_USER_ID = LAST_INSERT_ID();

    IF p_USER_TYPE = 'Renter' THEN
        INSERT INTO RENTER (USER_ID)
        VALUES (p_USER_ID);

        INSERT INTO RENTER_SETTINGS (USER_ID)
        VALUES (p_USER_ID);
    ELSEIF p_USER_TYPE = 'Landlord' THEN
        INSERT INTO LANDLORD (USER_ID)
        VALUES (p_USER_ID);
    END IF;

END$$

DELIMITER ;
