DELIMITER $$

CREATE PROCEDURE MAKE_LANDLORD(IN p_USER_ID INT UNSIGNED)
BEGIN

    IF NOT EXISTS (SELECT 1 FROM USERS WHERE USER_ID = p_USER_ID) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'User does not exist';
    END IF;

    IF EXISTS (SELECT 1 FROM LANDLORD WHERE USER_ID = p_USER_ID) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'User is already a landlord';
    END IF;


    INSERT INTO LANDLORD (USER_ID) VALUES (p_USER_ID);
END $$
DELIMITER ;