DELIMITER $$

CREATE PROCEDURE MAKE_RENTER(IN p_USER_ID INT UNSIGNED)
BEGIN

    IF NOT EXISTS (SELECT 1 FROM USERS WHERE USER_ID = p_USER_ID) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'User does not exist';
    END IF;

    IF EXISTS (SELECT 1 FROM RENTER WHERE USER_ID = p_USER_ID) THEN
        SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'User is already a RENTER';
    END IF;

    INSERT INTO RENTER (USER_ID) VALUES (p_USER_ID);
END $$
DELIMITER ;