-- TITLE: Fosgate_FIND_PROPS_BELOW_RENT_AMT
-- AUTHOR: Jeffrey Fosgate
-- DATE OF GITHUB COMMIT: 11/14/2025
-- A simple stored procedure for retrieving all property IDs whose rent costs are below a certain given amount.

DELIMITER $$
CREATE PROCEDURE FIND_PROPS_BELOW_RENT_AMT (
	IN RENT_MAX INT
)
BEGIN
	DROP TABLE IF EXISTS PROPS_BELOW_RENT_AMT;
	CREATE TABLE PROPS_BELOW_RENT_AMT (
		PROP_ID INT UNSIGNED PRIMARY KEY
	);
    INSERT INTO PROPS_BELOW_RENT_AMT
    SELECT PROP_ID
    FROM PROPERTY
    WHERE RENT_COST <= RENT_MAX;
END $$
