-- TITLE: SEARCH_PROCEDURES
-- AUTHOR: Sophia Priola
-- This procedure allows users to enter filters to their apartment search

DELIMITER $$

CREATE PROCEDURE SEARCH_PROPERTIES (
    IN P_CITY          VARCHAR(100),
    IN P_STATE_CODE    CHAR(2),
    IN P_MIN_RENT      INT,
    IN P_MAX_RENT      INT,
    IN P_MIN_SQFT      INT UNSIGNED,
    IN P_MIN_BEDROOMS  TINYINT UNSIGNED,
    IN P_MIN_BATHROOMS FLOAT(2,1),
    IN P_CAN_RENT      TINYINT(1)
)
BEGIN
    SELECT
        P.PROPERTY_ID,
        P.UNIT_LABEL,
        A.STREET,
        A.CITY,
        A.STATE_CODE,
        A.ZIPCODE,
        P.RENT_COST,
        P.SQFT,
        P.BEDROOMS,
        P.BATHROOMS,
        P.CAN_RENT
    FROM PROPERTY AS P
    JOIN ADDRESS AS A
        ON P.ADDR_ID = A.ADDR_ID
    WHERE
        (P_CITY IS NULL OR A.CITY = P_CITY)
        AND (P_STATE_CODE IS NULL OR A.STATE_CODE = P_STATE_CODE)
        AND (P_MIN_RENT IS NULL OR P.RENT_COST >= P_MIN_RENT)
        AND (P_MAX_RENT IS NULL OR P.RENT_COST <= P_MAX_RENT)
        AND (P_MIN_SQFT IS NULL OR P.SQFT >= P_MIN_SQFT)
        AND (P_MIN_BEDROOMS IS NULL OR P.BEDROOMS >= P_MIN_BEDROOMS)
        AND (P_MIN_BATHROOMS IS NULL OR P.BATHROOMS >= P_MIN_BATHROOMS)
        AND (P_CAN_RENT IS NULL OR P.CAN_RENT = P_CAN_RENT)
    ORDER BY
        P.RENT_COST ASC;
END$$

DELIMITER ;
