CREATE PROCEDURE SEND_NOTIFICATION (
  -- Variables in use 
  IN  p_TEXT  VARCHAR(1000),
  OUT p_NOTIFICATION_ID INT UNSIGNED
)
BEGIN
  INSERT INTO NOTIFICATION (TIME_STAMP, IS_READ, NOTIFICATION_TEXT)
  VALUES (CURRENT_TIMESTAMP, 0, p_TEXT);
  
END$$

DELIMITER ;
