CREATE PROCEDURE SEND_MESSAGE(
  -- Variables in use
  IN  p_SENDER_ID INT,
  IN  p_RECIPIENT_ID INT,
  IN  p_MESSAGE_TEXT VARCHAR(1000),
  OUT p_MSG_ID INT UNSIGNED
)
BEGIN 
-- Insert variables into 
INSERT INTO MESSAGE (SENDER_ID, RECIPIENT_ID, SENT_TIMESTAMP, MESSAGE_TEXT, IS_READ)
  VALUES (p_SENDER_ID, p_RECIPIENT_ID, CURRENT_TIMESTAMP, p_MESSAGE_TEXT, 0) ;
  
END$$

DELIMITER ;
