CREATE PROCEDURE SUBMIT_REVIEW(
	-- Variables included 
	IN p_REVIEW_ID INT UNSIGNED ,
	IN p_USER_ID INT UNSIGNED ,
	IN p_PROPERTY_ID INT UNSIGNED , 
    IN p_COMMENT VARCHAR(1000) , 
    IN p_STARS TINYINT UNSIGNED
    )
BEGIN 
	-- INSERT VALUES INTO 
    INSERT INTO REVIEW(REVIEW_ID, USER_ID, PROPERTY_ID, COMMENT, STARS)
    VALUES (p_REVIEW_ID, p_USER_ID, p_PROPERTY_ID, p_COMMENT, p_STARS);
END$$
    
DELIMITER ;

    
    
    
