-- NAME: PROP_PRICE_HISTORY.sql
-- AUTHOR: Jeffrey Fosgate
-- DATE: December 6, 2025
-- DESCRIPTION: A simple schema that tracks a property's price history over time, in coordination with ADD_PROP_PRICE_HISTORY.sql.

CREATE TABLE IF NOT EXISTS PROP_PRICE_HISTORY (
	ENTRY_ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    PROP_ID INT UNSIGNED NOT NULL,
    RENT_COST INT UNSIGNED NOT NULL,
    PRICE_START DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (PROP_ID)
    REFERENCES PROPERTY (PROP_ID)
);
