CREATE TABLE IF NOT EXISTS RENTER_SETTINGS (
    USER_ID INT UNSIGNED PRIMARY KEY,
    DISTANCE_MAX INT NOT NULL,
    GENDER_PREFERRED CHAR(1) NOT NULL,
    CHECK (GENDER_PREFERRED IN ('M' , 'F', 'X', '?')),
    FOREIGN KEY (USER_ID) 
		REFERENCES USERS (USER_ID)
		ON DELETE CASCADE ON UPDATE CASCADE
);
