-- Creates table for required renter settings (e.g. max distance to search)
CREATE TABLE IF NOT EXISTS RENTER_SETTINGS (
    USER_ID INT UNSIGNED PRIMARY KEY,
    DISTANCE_MAX INT,
    GENDER_PREFERRED CHAR(1),
    CHECK (GENDER_PREFERRED IN ('M' , 'F', 'X', '?')),
    FOREIGN KEY (USER_ID) 
		REFERENCES USERS (USER_ID)
		ON DELETE CASCADE ON UPDATE CASCADE
);
