-- Creates table for storing user preferences (e.g. likes sports)
CREATE TABLE IF NOT EXISTS RENTER_PREFERENCES (
    PREFERENCE_ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    PREFERENCE_NAME VARCHAR(100) NOT NULL
);
