-- TITLE: REVIEW.sql
-- AUTHOR: Sophia Priola
-- Table creation of review

CREATE TABLE IF NOT EXISTS REVIEW (
  USER_ID INT UNSIGNED,
  PROPERTY_ID INT UNSIGNED,
  COMMENTS VARCHAR(1000),
  STARS FLOAT(2, 1) UNSIGNED NOT NULL,
  CHECK (STARS BETWEEN 1 AND 5), 
  CONSTRAINT PK_REVIEW PRIMARY KEY (USER_ID, PROPERTY_ID),
  FOREIGN KEY (USER_ID)
  REFERENCES USERS (USER_ID),
  FOREIGN KEY (PROPERTY_ID)
  REFERENCES PROPERTY (PROPERTY_ID)
);
