CREATE TABLE IF NOT EXISTS ADDRESS (
	ADDR_ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    STREET VARCHAR(200) NOT NULL,
	CITY VARCHAR(100) NOT NULL,
	STATE_CODE CHAR(2) NOT NULL,
	ZIPCODE CHAR(5) NOT NULL,
);
