CREATE TABLE IF NOT EXISTS HAS_PREFERENCE (
    USER_ID INT UNSIGNED PRIMARY KEY,
    PREFERENCE_ID INT UNSIGNED PRIMARY KEY,
    FOREIGN KEY (USER_ID) 
		REFERENCES USERS (USER_ID)
		ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (PREFERENCE_ID) 
		REFERENCES RENTER_PREFERENCES (PREFERENCE_ID)
);
