CREATE TABLE IF NOT EXISTS INTERUSER (
  RENTER_ID INT UNSIGNED,
  CONNECTION_ID INT UNSIGNED,
  SWIPED BOOL NOT NULL,
  BLOCKED BOOL NOT NULL DEFAULT 0,
  CONSTRAINT PK_INTERUSER PRIMARY KEY (RENTER_ID, CONNECTION_ID),
  FOREIGN KEY (RENTER_ID)
  REFERENCES RENTER (USER_ID)
  ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (CONNECTION_ID)
  REFERENCES RENTER (USER_ID)
  ON DELETE CASCADE ON UPDATE CASCADE
);