-- TITLE: MESSAGE.sql
-- AUTHOR: Sophia Priola
-- Table creation for message 

CREATE TABLE IF NOT EXISTS MESSAGE (
	MSG_ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,		-- Unique message ID 
	SENDER_ID INT UNSIGNED NOT NULL,	-- The user sending the message ID 
	RECIPIENT_ID INT UNSIGNED NOT NULL,	-- The user recieving the message ID
	TIME_STAMP TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,	-- Timestamp for when message sent
	MESSAGE_TEXTS VARCHAR(1000) CHARACTER SET utf8mb4 NOT NULL,	-- Text within the message 
	IS_READ TINYINT(1) NOT NULL DEFAULT 0,	-- If message read 1, if not 0
	-- SENDER_ID and RECIPIENT_ID foreign from USER
	FOREIGN KEY (SENDER_ID) 
		REFERENCES USERS(USER_ID)
		ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (RECIPIENT_ID) 
		REFERENCES USERS(USER_ID)
		ON DELETE CASCADE ON UPDATE CASCADE
);
