CREATE TABLE IF NOT EXISTS PROPERTY (
	PROPERTY_ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    RENT_COST INT UNSIGNED NOT NULL,
    PROPERTY_RATING FLOAT(2, 1),
    LANDLORD_ID INT UNSIGNED,
    SQFT INT UNSIGNED,
    BATHROOMS FLOAT(2, 1) UNSIGNED,
    BEDROOMS FLOAT(2, 1) UNSIGNED,
    CAN_RENT TINYINT(1) NOT NULL DEFAULT 0,
    UNIT_LABEL VARCHAR(50),
    ADDR_ID INT UNSIGNED NOT NULL,
    FOREIGN KEY (LANDLORD_ID) 
		REFERENCES LANDLORD (USER_ID),
	FOREIGN KEY (ADDR_ID) 
		REFERENCES ADDRESS (ADDR_ID),
    CHECK (PROPERTY_RATING >= 0.0 AND PROPERTY_RATING <= 5.0)
);
