CREATE INDEX IDX_USERNAME ON USERS(USERNAME);
CREATE INDEX IDX_GENDER ON USERS(GENDER);
CREATE INDEX IDX_BIRTHDATE ON USERS(BIRTH_DATE);

CREATE INDEX IDX_NOTIFICATION_TIMESTAMP ON NOTIFICATION(TIME_STAMP);

CREATE INDEX IDX_MESSAGE_TIMESTAMP ON MESSAGE(SENT_TIMESTAMP);

CREATE INDEX IDX_CITY ON ADDRESS(CITY);