CREATE TABLE MATCH(
	MATCH_ID INT UNSIGNED PRIMARY KEY,
    RENTER_ID INT UNSIGNED PRIMARY KEY, 
    FOREIGN KEY (RENTER_ID) REFERENCES RENTER(USER_ID)
    ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (MATCH_ID) REFERENCES RENTER(USER_ID)
    ON DELETE CASCADE ON UPDATE CASCADE,
    CHECK (MATCH_ID <> RENTER_ID),
    UNIQUE KEY ux_um_pair (pair_a, pair_b)

);
