CREATE TABLE MESSAGE (
    MSG_ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    SENDER_ID INT NOT NULL,
    RECIPIENT_ID INT NOT NULL,
    SENT_TIMESTAMP TIMESTAMP NOT NULL,
    MESSAGE_TEXT NVARCHAR(1000) NOT NULL,
    IS_READ BOOL NOT NULL,
    FOREIGN KEY (SENDER_ID) REFERENCES USER (USER_ID),
    FOREIGN KEY (RECIPIENT_ID) REFERENCES USER (USER_ID)
);
    
    
    

	