CREATE TABLE NOTIFIES (
	NOTIFICATION_ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT, 
    USER_ID INT UNSIGNED PRIMARY KEY,
    FOREIGN KEY (NOTIFICATION_ID) REFERENCES NOTIFICATION (NOTIFICATION_ID),
    FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID)
    );