CREATE TABLE PROPERTY (
	PROPERTY_ID INT UNSIGNED UNIQUE NOT NULL AUTO_INCREMENT,
    RENT_COST INT UNSIGNED NOT NULL,
    PROPERTY_RATING FLOAT(1,2),
    LANDLORD_ID INT UNSIGNED,
    BATHROOMS SMALLINT UNSIGNED NOT NULL,
    BEDROOMS SMALLINT UNSIGNED NOT NULL,
    CAN_RENT BOOL NOT NULL,
    APT_NUM INT UNSIGNED,
    ADDR INT UNIQUE NOT NULL,
    PRIMARY KEY (PROPERTY_ID),
    FOREIGN KEY (LANDLORD_ID) REFERENCES LANDLORD (USER_ID),
	FOREIGN KEY (ADDR) REFERENCES ADDRESS (ADDR_ID),
    CHECK (PROPERTY_RATING >= 0.0 AND PROPERTY_RATING <= 5.0)
);