CREATE TABLE REVIEW (
    REVIEW_ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT ,
    USER_ID INT UNSIGNED NOT NULL,
    PROPERTY_ID INT UNSIGNED NOT NULL,
    COMMENTS VARCHAR(1000),
    STARS TINYINT UNSIGNED NOT NULL,
    CONSTRAINT CHECK_STARS CHECK (STARS BETWEEN 1 AND 5), 
    CONSTRAINT UNQ_USER_PROPERTY UNIQUE (USER_ID, PROPERTY_ID), 
    FOREIGN KEY (USER_ID)
        REFERENCES USERS (USER_ID),
    FOREIGN KEY (PROPERTY_ID)
        REFERENCES PROPERTY (PROPERTY_ID)
);