CREATE TABLE IF NOT EXISTS USERS (
	USER_ID INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(50) NOT NULL UNIQUE,
   	PASS_WORD VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
    PHONE_NUMBER INT NOT NULL,
    GENDER CHAR(1) NOT NULL,
    USER_DESC NVARCHAR(1000),
    PICTURE_URL NVARCHAR(1000),
    BIRTH_DATE DATE NOT NULL,
    DISPLAY_NAME VARCHAR(200) NOT NULL,
	CONSTRAINT CHK_GENDER CHECK (GENDER IN ('M' , 'F', 'X', '?'))
);
